### ISSUE TITLE
problem with running train.py

### ISSUE THREAD

**Issue by nupnup-goddamn** [kprokofi/light-weight-face-anti-spoofing#14] opened 2021-03-21 18:04 UTC
Hi I ran into this error message while running train.py. 
The training was able to run smoothly at the start but will somehow end abruptly with the error message:

    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/students/acct1002_03/fyp/fyp/linuxEnv/light-weight-face-anti-spoofing/datasets/celeba_spoof.py", line 50, in __getitem__
    data_item = self.data[str(idx)]
KeyError: '4046'

This error will surface whenever the training process is still on its first epoch. For instance, before the training progress gets to 100%, it will abruptly bring up this error. 

How will u propose to solve this issue? 

Thank you in advance!

**Comment by mrtrunghieu1** [comment] 2021-03-23 19:13
I met the same problem. How will u propose to solve this issue?

**Comment by kprokofi** [comment] 2021-03-23 19:23
Hi, I will take a look in the coming days at this problem and try to reproduce this issue

**Comment by mrtrunghieu1** [comment] 2021-03-24 03:08
Hope you will deal with this issue sooner.
Thank you in advance!

**Comment by nupnup-goddamn** [comment] 2021-03-24 07:35
Hi I think the problem was due to the reading of folder 4046 from ./CelebA_Spoof/CelebA_Spoof/Data/train/4046.
This was inferred from the error message:
File "/home/students/acct1002_03/fyp/fyp/linuxEnv/light-weight-face-anti-spoofing/datasets/celeba_spoof.py", line 50, in getitem
data_item = self.data[str(idx)]
KeyError: '4046'

I get past this error by simply skipping this particularly by adding (in celeba_spoof.py, line 49):
 _def __getitem__(self, idx):_
        **if idx==4046:
            idx+=1**
        _data_item = self.data[str(idx)]
        img = cv.imread(os.path.join(self.root_folder, data_item['path']))
        bbox = data_item['bbox']_

when idx is 4046, it will simply skip the folder to 4047. 
This will allow you to move on from this error and train to epoch 1/71. 

Lemme know if it solves for u as well. so that i can close this issue

**Comment by nupnup-goddamn** [comment] 2021-03-24 10:45
![Epoch1_error](https://user-images.githubusercontent.com/72186708/112297159-81945400-8cd0-11eb-95c6-b5ccffd5311a.PNG)

After getting past the first issue of train.py, I am able to train past epoch 0/71 but i am not able to get past epoch 1/71 due to this error above.

its weird because if i am able to get past epoch 0/71, i should be able to get past any other epoch as well.  below is my config.py code
[config.txt](https://github.com/kprokofi/light-weight-face-anti-spoofing/files/6196422/config.txt)


How can i resolve this?

**Comment by nupnup-goddamn** [comment] 2021-03-24 16:34
Hi an update on the issue regarding "max_epoch" above. 

I found a typo issue in trainer.py line 171. 
It should be: 

def eval(self, epoch: int, epoch_accuracy: float, save_chkpt: bool=True):
       if (epoch%10 == 0 or epoch >= (**self.config.epochs.max_epoch** - 10)) and (epoch_accuracy > self.current_accuracy):

**Comment by mrtrunghieu1** [comment] 2021-03-29 03:30
Hi there! I have a small issue:
If I have only 1 data set "Celeba_spoof" consis of: train and test folder.
How can I get a val folder for training?
I don't want to have val and test the same because my evaluation will be inaccurate.

**Closed** 2021-04-07 22:43 UTC
